version: "3.9"
services:
  mongo-database:
    image: ucd-emp-wellness-db:lts
    container_name: ucd-emp-wellness-db
    build: ./mongo-db/
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - "27017:27017"
    restart: unless-stopped
    volumes: 
      - mongodb:/data/db
    networks:
      - dev_network
  express-api:
    image: final_iteration_api_dev:lts
    hostname: final-iteration
    container_name: ucd-wellness-api
    build: 
      context: ./mongo-api/
      dockerfile: dockerfile.dev
    environment:
      - "NODE_ENV=development"
      - "PORT=${PORT}"
      - "MONGODB_URL_DEV=${MONGODB_URL_DEV}"
      - "DEBUG=${DEBUG}"
      - "JWT_SECRET=${JWT_SECRET}"
      - "JWT_ACCESS_EXPIRATION_MINUTES=${JWT_ACCESS_EXPIRATION_MINUTES}"
      - "JWT_REFRESH_EXPIRATION_DAYS=${JWT_REFRESH_EXPIRATION_DAYS}"
      - "JWT_RESET_PASSWORD_EXPIRATION_MINUTES=${JWT_RESET_PASSWORD_EXPIRATION_MINUTES}"
      - "JWT_VERIFY_EMAIL_EXPIRATION_MINUTES=${JWT_VERIFY_EMAIL_EXPIRATION_MINUTES}"
      - "CERTIFICATE=${CERTIFICATE}"
    ports:
      - "3005:3005"
    volumes:
      - ./mongo-api:/usr/src/app
      - api_node_modules:/usr/src/cache
    restart: unless-stopped
    networks:
      - dev_network

volumes: 
  api_node_modules:
  mongodb:

networks:
  dev_network:
    external: true